name: "EKS Deploy"
description: "Deploys a dockerized application to a Kubernetes cluster"
inputs:
  aws-access-key-id:
    description: "AWS Access Key for deploying to cluster"
    required: true
  aws-secret-access-key:
    description: "AWS Access Secret for deploying to cluster"
    required: true
  aws-region:
    description: "AWS Region for cluster"
    required: true
    default: us-east-1
  ecr-repository:
    description: "ECR repository for the docker image"
    required: true
  deployment-folder:
    description: "Location of the k8s files"
    required: true
  cluster-name:
    description: "Name of the k8s cluster"
    required: true
runs:
  using: "composite"
  steps:
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ inputs.aws-access-key-id }}
        aws-secret-access-key: ${{ inputs.aws-secret-access-key }}
        aws-region: ${{ inputs.aws-region }}

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1

    - name: Set up Docker Buildx
      id: buildx
      uses: docker/setup-buildx-action@v1

    - name: Build, tag, and push image to ECR
      uses: docker/build-push-action@v2
      env:
        IMAGE_TAG: ${{ github.sha }}
        IMAGE: ${{ steps.login-ecr.outputs.registry }}/${{ inputs.ecr-repository }}
      with:
        context: .
        push: true
        tags: |
          ${{ env.IMAGE }}:${{ env.IMAGE_TAG }}
          ${{ env.IMAGE }}:latest
        cache-from: type=gha
        cache-to: type=gha,mode=max

    - name: Setup yq
      shell: bash
      run: |
        sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys CC86BB64
        sudo add-apt-repository ppa:rmescandon/yq
        sudo apt update
        sudo apt install yq -y

    - name: Update deployment image
      env:
        DEPLOYMENT_FOLDER: ${{ inputs.deployment-folder }}
        SHA_IMAGE: ${{ steps.login-ecr.outputs.registry }}/${{ inputs.ecr-repository }}:${{ github.sha }}
      shell: bash
      run: |
        yq e -i '(.spec.template.spec.containers[0].image) = strenv(SHA_IMAGE)' $DEPLOYMENT_FOLDER/deployment.yml

    - name: Setup kubectl
      shell: bash
      run: |
        sudo apt-get install -y apt-transport-https ca-certificates curl
        sudo curl -fsSLo /usr/share/keyrings/kubernetes-archive-keyring.gpg https://packages.cloud.google.com/apt/doc/apt-key.gpg
        echo "deb [signed-by=/usr/share/keyrings/kubernetes-archive-keyring.gpg] https://apt.kubernetes.io/ kubernetes-xenial main" | sudo tee /etc/apt/sources.list.d/kubernetes.list
        sudo apt-get update
        sudo apt-get install -y kubectl

    - name: Deploy to EKS
      shell: bash
      env:
        DEPLOYMENT_FOLDER: ${{ inputs.deployment-folder }}
        CLUSTER: ${{ inputs.cluster-name }}
      run: |
        aws eks update-kubeconfig --name $CLUSTER
        kubectl apply -f $DEPLOYMENT_FOLDER
        kubectl rollout status -f $DEPLOYMENT_FOLDER

