name: "EKS Deploy"
description: "Deploys a dockerized application to a Kubernetes cluster"
inputs:
  service-name:
    description: "Name of the deployed service. Also the name of the ECR repository"
    required: true
  cluster-name:
    description: "Name of the k8s cluster"
    required: true
  helm-chart:
    description: "Location of the helm chart"
    required: true
    default: ./deployment/helm
  helm-values:
    description: "Location of the helm values file"
    required: true
  aws-access-key-id:
    description: "AWS Access Key for deploying to cluster"
    required: true
  aws-secret-access-key:
    description: "AWS Access Secret for deploying to cluster"
    required: true
  aws-region:
    description: "AWS Region for cluster"
    required: true
    default: us-east-1
runs:
  using: "composite"
  steps:
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ inputs.aws-access-key-id }}
        aws-secret-access-key: ${{ inputs.aws-secret-access-key }}
        aws-region: ${{ inputs.aws-region }}

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1

    - name: Set up Docker Buildx
      id: buildx
      uses: docker/setup-buildx-action@v1

    - name: Build, tag, and push image to ECR
      uses: docker/build-push-action@v2
      env:
        IMAGE_TAG: ${{ github.sha }}
        IMAGE: ${{ steps.login-ecr.outputs.registry }}/${{ inputs.service-name }}
      with:
        context: .
        push: true
        tags: |
          ${{ env.IMAGE }}:${{ env.IMAGE_TAG }}
          ${{ env.IMAGE }}:${{ inputs.cluster-name }}
        cache-from: type=gha
        cache-to: type=gha,mode=max

    - name: Setup Helm
      uses: azure/setup-helm@v1

    - name: Deploy Chart
      env:
        CLUSTER_NAME: ${{ inputs.cluster-name }}
        SERVICE_NAME: ${{ inputs.service-name }}
        HELM_CHART: ${{ inputs.helm-chart }}
        HELM_VALUES: ${{ inputs.helm-values }}
        SHA_IMAGE: ${{ steps.login-ecr.outputs.registry }}/${{ inputs.service-name }}:${{ github.sha }}
      shell: bash
      run: |
        aws eks update-kubeconfig --name $CLUSTER_NAME
        export VERSION=$(git describe --tags --exact-match HEAD || git rev-parse HEAD) 2> /dev/null
        sed -i "s/^appVersion:.*$/appVersion: \"$VERSION\"/" $HELM_CHART/Chart.yaml
        helm upgrade $SERVICE_NAME $HELM_CHART --install --atomic --create-namespace -f $HELM_VALUES --set image=$SHA_IMAGE --set version=$VERSION