name: "EKS Deploy"
description: "Deploys a dockerized application to a Kubernetes cluster"
inputs:
  service-name:
    description: "Name of the deployed service. Also the name of the ECR repository"
    required: true
  cluster-name:
    description: "Name of the k8s cluster"
    required: true
  helm-chart:
    description: "Location of the helm chart"
    required: true
    default: ./deployment/helm
  helm-values:
    description: "Location of the helm values file"
    required: true
  aws-access-key-id:
    description: "AWS Access Key for deploying to cluster"
    required: true
  aws-secret-access-key:
    description: "AWS Access Secret for deploying to cluster"
    required: true
  aws-region:
    description: "AWS Region for cluster"
    required: true
    default: us-east-1
  version:
    description: "Version to be deployed. If currently deployed version matches, deployment is skipped"
    required: true
    default: ""
  env:
    description: "Environment to build for"
    required: true
    default: ""
  slack-webhook:
    description: "Slack webhook URL for notification of status"
    required: true
outputs:
  skipped:
    description: "Whether deployment was skipped"
    value: ${{ steps.check.outputs.skip }}
runs:
  using: "composite"
  steps:
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ inputs.aws-access-key-id }}
        aws-secret-access-key: ${{ inputs.aws-secret-access-key }}
        aws-region: ${{ inputs.aws-region }}

    - name: Get current ref
      id: current-ref
      shell: bash
      run: |
        export REF=$(git describe --tags --exact-match HEAD || git rev-parse HEAD) 2> /dev/null
        export HEAD=$(git rev-parse HEAD) 2> /dev/null
        export MESSAGE=$(git show -s --format=%s) 2> /dev/null
        echo "::set-output name=value::$REF"
        echo "::set-output name=head::$HEAD"
        echo "::set-output name=message::$MESSAGE"

    - name: Setup Helm
      uses: azure/setup-helm@v1

    - name: Setup kubeconfig
      shell: bash
      run: aws eks update-kubeconfig --name ${{ inputs.cluster-name }}

    - name: Get deployed values
      shell: bash
      run: |
        touch helm-values.yml
        helm get values ${{ inputs.service-name }} -o yaml >> helm-values.yml || true

    - name: Get deployed ref
      id: deployed-ref
      uses: mikefarah/yq@master
      with:
        cmd: yq eval '.version' 'helm-values.yml'

    - name: Check version
      id: check
      shell: bash
      run: |
        echo "::set-output name=skip::$([ ${{ steps.current-ref.outputs.value }} == ${{ steps.deployed-ref.outputs.result }} ] && echo 'true' || echo 'false')"

    - name: Existence of Build Script
      id: build-script
      shell: bash
      run: |
        [ -d "./.github/build" ] && echo echo "::set-output name=exists::1" || echo "::set-output name=exists::0"

    - name: Run Build Script
      if: steps.build-script.outputs.exists == '1' && steps.check.outputs.skip == 'false'
      uses: ./.github/buildsjdalfk
      with:
        env: ${{ inputs.env }}

    - name: Login to Amazon ECR
      if: steps.check.outputs.skip == 'false'
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1

    - name: Set up Docker Buildx
      if: steps.check.outputs.skip == 'false'
      id: buildx
      uses: docker/setup-buildx-action@v1

    - name: Build, tag, and push image to ECR
      if: steps.check.outputs.skip == 'false'
      uses: docker/build-push-action@v2
      env:
        IMAGE_TAG: ${{ github.sha }}
        IMAGE: ${{ steps.login-ecr.outputs.registry }}/${{ inputs.service-name }}
      with:
        context: .
        push: true
        tags: |
          ${{ env.IMAGE }}:${{ env.IMAGE_TAG }}
          ${{ env.IMAGE }}:${{ inputs.cluster-name }}
        cache-from: type=gha
        cache-to: type=gha,mode=max

    - name: Deploy Chart
      if: steps.check.outputs.skip == 'false'
      id: deployment
      env:
        SERVICE_NAME: ${{ inputs.service-name }}
        HELM_CHART: ${{ inputs.helm-chart }}
        SHA_IMAGE: ${{ steps.login-ecr.outputs.registry }}/${{ inputs.service-name }}:${{ github.sha }}
        VERSION: ${{ steps.current-ref.outputs.value }}
      shell: bash
      run: |
        sed -i "s/^appVersion:.*$/appVersion: \"$VERSION\"/" $HELM_CHART/Chart.yaml
        helm upgrade $SERVICE_NAME $HELM_CHART --install --atomic --create-namespace -f ./deployment/values/${{ inputs.env }}.yml --set image=$SHA_IMAGE --set version=$VERSION
        echo "::set-output name=success::1"

    - name: Determine Deployment Status
      if: always() && steps.check.outputs.skip == 'false'
      id: run-status
      shell: bash
      run: |
        [ ${{ steps.deployment.outputs.success == '1' }} ] && echo "::set-output name=value::success" || echo "::set-output name=value::failure"

    - name: Notify of Deployment
      uses: ravsamhq/notify-slack-action@v1
      if: always() && steps.check.outputs.skip == 'false'
      with:
        status: ${{ steps.run-status.outputs.value }}
        notification_title: '<${{ github.server_url }}/InvictusApps/${{ inputs.service-name }}|${{ inputs.service-name }}> {status_message} deployment to *${{ inputs.cluster-name }}*'
        message_format: '{emoji} *${{ steps.current-ref.outputs.message }}*'
        footer: '<${{ github.server_url }}/InvictusApps/${{ inputs.service-name }}/commit/${{ steps.current-ref.outputs.head }}|View Head Commit>  | <${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}|View {workflow} Run>'
      env:
        SLACK_WEBHOOK_URL: ${{ inputs.slack-webhook }}